import collections
"""
https://leetcode.com/problems/find-the-difference/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

https://discuss.leetcode.com/topic/57651/3-different-python-solutions-dictionary-difference-xor

https://discuss.leetcode.com/topic/55918/1-liners-and-2-liner-in-python
"""
def find_the_difference(s, t):
    d = {}

    for char in t:
        d[char] = d.get(char, 0) + 1

    for char in s:
        if char in d:
            d[char] -= 1

    for key, value in d.items():
        if value == 1:
            return key

def find_the_difference_3(s, t):
    dic = {}

    for ch in s:
        dic[ch] = dic.get(ch, 0) + 1
    for ch in t:
        if dic.get(ch, 0) == 0:
            return ch
        dic[ch] -= 1

def find_the_difference_2(s, t):
    return list((collections.Counter(t) - collections.Counter(s)))[0]


if __name__ == '__main__':
    print find_the_difference('abcd', 'abcde')
    print find_the_difference('a', 'aa')
